apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fedora-base
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fedora-base
    app.kubernetes.io/part-of: workstation-ostree-config
  name: fedora-base
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: fedora-base
status:
  loadBalancer: {}
